# Generated by Django 5.2.7 on 2025-10-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_connect', '0002_remove_message_group_studygroup_groupmessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Group Messages'},
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
